"""
MANUSCRIPT_TITLE
Output: OUTFILE_NAME

Generated by /literature:manuscript. Replace Lorem ipsum sections with actual content.
Citations: use [@slug] inline in add_para() calls. Run /literature:claim-audit when done.
"""

import re, os
from docx import Document
from docx.shared import Pt, Cm, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

HERE    = os.path.dirname(os.path.abspath(__file__))
OUTFILE = os.path.join(HERE, "OUTFILE_NAME")

# ── Citation config ────────────────────────────────────────────────────────────
CITATION_STYLE = "numbered"   # "numbered" | "author-year" | "alpha"
BIB_PATH = os.path.join(HERE, "references", "key_papers.bib")

def load_bib(path):
    """Parse key_papers.bib → {key: {doi, year, author, annote}} dict."""
    if not os.path.exists(path):
        return {}
    with open(path, encoding='utf-8') as f:
        raw = f.read()
    entries = {}
    for block in re.split(r'\n(?=@)', raw):
        block = block.strip()
        if not block:
            continue
        m = re.match(r'@\w+\{([^,]+),', block)
        if not m:
            continue
        key = m.group(1).strip()
        def _field(name, text):
            pat = re.search(rf'\b{name}\s*=\s*\{{(.*?)\}}\s*[,\n}}]', text, re.DOTALL)
            return pat.group(1).strip() if pat else ''
        entries[key] = {
            'doi':    _field('doi',    block),
            'year':   _field('year',   block),
            'author': _field('author', block),
            'annote': _field('annote', block),
        }
    return entries

_bib       = load_bib(BIB_PATH)
_cites     = {}
_cite_order = []

def _resolve_key(key):
    if key not in _cites:
        _cites[key] = len(_cites) + 1
        _cite_order.append(key)
    return _cites[key]

def validate_citations(cites_used, bib):
    if not bib:
        return
    undefined = [k for k in cites_used if k not in bib]
    if undefined:
        raise SystemExit(f'UNDEFINED CITATION KEYS: {undefined}')
    orphans = [k for k in bib if k not in cites_used]
    if orphans:
        print(f'WARNING: orphan bib entries: {orphans}')

_CITE_SOURCE = []


# ── Helpers ───────────────────────────────────────────────────────────────────

def set_line_spacing(paragraph, spacing=2.0):
    pPr = paragraph._p.get_or_add_pPr()
    lSpc = OxmlElement('w:spacing')
    lSpc.set(qn('w:line'), str(int(spacing * 240)))
    lSpc.set(qn('w:lineRule'), 'auto')
    pPr.append(lSpc)

def add_run_with_font(paragraph, text, bold=False, italic=False,
                      superscript=False, size_pt=12):
    run = paragraph.add_run(text)
    run.bold = bold
    run.italic = italic
    run.font.size = Pt(size_pt)
    if superscript:
        run.font.superscript = True
    return run

def resolve_cites(text):
    pattern = re.compile(r'\[@([^\]]+)\]')
    parts, last = [], 0
    for m in pattern.finditer(text):
        if m.start() > last:
            parts.append((text[last:m.start()], False))
        keys = [k.strip().lstrip('@') for k in m.group(1).split(';')]
        nums = [str(_resolve_key(k) if k in _bib else f'?{k}?') for k in keys]
        parts.append((','.join(nums), True))
        last = m.end()
    if last < len(text):
        parts.append((text[last:], False))
    return parts

def _add_inline_formatted(paragraph, text, base_bold=False,
                           base_italic=False, size_pt=12):
    pattern = re.compile(r'\*\*(.+?)\*\*|\*(.+?)\*')
    last = 0
    for m in pattern.finditer(text):
        if m.start() > last:
            add_run_with_font(paragraph, text[last:m.start()],
                              bold=base_bold, italic=base_italic, size_pt=size_pt)
        if m.group(1) is not None:
            add_run_with_font(paragraph, m.group(1), bold=True,
                              italic=base_italic, size_pt=size_pt)
        else:
            add_run_with_font(paragraph, m.group(2), bold=base_bold,
                              italic=True, size_pt=size_pt)
        last = m.end()
    if last < len(text):
        add_run_with_font(paragraph, text[last:], bold=base_bold,
                          italic=base_italic, size_pt=size_pt)

def add_para(doc, text, bold=False, italic=False,
             alignment=WD_ALIGN_PARAGRAPH.LEFT, space_before=0, size_pt=12):
    _CITE_SOURCE.append(text)
    p = doc.add_paragraph()
    p.alignment = alignment
    if space_before:
        p.paragraph_format.space_before = Pt(space_before)
    set_line_spacing(p)
    for chunk, is_sup in resolve_cites(text.strip()):
        if is_sup:
            add_run_with_font(p, chunk, superscript=True, size_pt=size_pt)
        else:
            _add_inline_formatted(p, chunk, base_bold=bold,
                                  base_italic=italic, size_pt=size_pt)
    return p

def add_heading(doc, text, level=1, size_pt=None, bold=True):
    sizes = {1: 14, 2: 12, 3: 12}
    sz = size_pt or sizes.get(level, 12)
    p = doc.add_paragraph()
    set_line_spacing(p)
    run = p.add_run(text)
    run.bold = bold
    run.italic = (level == 3)
    run.font.size = Pt(sz)
    if level == 1:
        p.paragraph_format.space_before = Pt(12)
    elif level == 2:
        p.paragraph_format.space_before = Pt(6)
    return p

def set_doc_margins(doc):
    for section in doc.sections:
        section.top_margin    = Cm(2.54)
        section.bottom_margin = Cm(2.54)
        section.left_margin   = Cm(2.54)
        section.right_margin  = Cm(2.54)

def add_table_note(doc, text, size_pt=9):
    p = doc.add_paragraph()
    set_line_spacing(p)
    run = p.add_run(text)
    run.font.size = Pt(size_pt)
    run.italic = True

FIG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "figures")

def add_figure_legend(doc, num, caption, img_file=None):
    doc.add_paragraph()
    if img_file:
        img_path = os.path.join(FIG_DIR, img_file)
        if os.path.exists(img_path):
            p_img = doc.add_paragraph()
            p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run_img = p_img.add_run()
            run_img.add_picture(img_path, width=Inches(6.0))
    p = doc.add_paragraph()
    set_line_spacing(p)
    p.paragraph_format.left_indent = Cm(0)
    bold_run = p.add_run(f"Figure {num}. ")
    bold_run.bold = True
    bold_run.font.size = Pt(11)
    cap_run = p.add_run(caption)
    cap_run.font.size = Pt(11)
    doc.add_paragraph()
    return p

def make_table(doc, headers, rows, col_widths_cm=None,
               header_size=10, body_size=10,
               bold_section_rows=None, bold_data_rows=None,
               bold_data_cols=None):
    ncols = len(headers)
    tbl   = doc.add_table(rows=1 + len(rows), cols=ncols)
    tbl.style = 'Table Grid'
    for ci, h in enumerate(headers):
        cell = tbl.rows[0].cells[ci]
        cell.text = ''
        run = cell.paragraphs[0].add_run(h)
        run.bold = True
        run.font.size = Pt(header_size)
    for ri, row_data in enumerate(rows):
        is_sec = (bold_section_rows and ri in bold_section_rows)
        for ci, val in enumerate(row_data):
            cell = tbl.rows[ri + 1].cells[ci]
            cell.text = ''
            run = cell.paragraphs[0].add_run(str(val) if val is not None else '')
            run.font.size = Pt(body_size)
            if is_sec:
                run.bold = True
                run.italic = True
            if (bold_data_rows and ri in bold_data_rows
                    and bold_data_cols and ci in bold_data_cols):
                run.bold = True
    if col_widths_cm:
        for ci, w in enumerate(col_widths_cm):
            for row in tbl.rows:
                row.cells[ci].width = Cm(w)
    return tbl

def add_table_heading(doc, title):
    p = doc.add_paragraph()
    set_line_spacing(p)
    p.paragraph_format.space_before = Pt(12)
    run = p.add_run(title)
    run.bold = True
    run.font.size = Pt(11)
    return p


# ── Document setup ────────────────────────────────────────────────────────────

doc = Document()
set_doc_margins(doc)

style = doc.styles['Normal']
style.font.name = 'Times New Roman'
style.font.size = Pt(12)


# ── Title page ────────────────────────────────────────────────────────────────

# Title — centered
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
set_line_spacing(p)
run = p.add_run("MANUSCRIPT_TITLE")
run.bold = True
run.font.size = Pt(14)

# Short title — left
doc.add_paragraph()
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.LEFT
set_line_spacing(p)
run = p.add_run("Short title: MANUSCRIPT_SHORT_TITLE")
run.italic = True
run.font.size = Pt(11)

# Authors — left, with superscripts
doc.add_paragraph()
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.LEFT
set_line_spacing(p)
def _sup(para, text, size=10):
    r = para.add_run(text); r.font.size = Pt(size); r.font.superscript = True
def _reg(para, text, size=12, italic=False):
    r = para.add_run(text); r.font.size = Pt(size); r.italic = italic

_reg(p, "[Author 1]", italic=True);        _sup(p, "1")
_reg(p, ", [Author 2]", italic=True);      _sup(p, "2")
_reg(p, ", [Corresponding Author]", italic=True); _sup(p, "1"); _reg(p, "†")

# Affiliations — left, 10pt
doc.add_paragraph()
_affiliations = [
    ("1", "[Affiliation 1 — Department, Institution, City, Country]"),
    ("2", "[Affiliation 2 — Department, Institution, City, Country]"),
]
for num, aff_text in _affiliations:
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    set_line_spacing(p)
    r = p.add_run(num); r.font.size = Pt(10); r.font.superscript = True
    r = p.add_run(" " + aff_text); r.font.size = Pt(10)

# Corresponding author — left
doc.add_paragraph()
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.LEFT
set_line_spacing(p)
run = p.add_run(
    "†Corresponding author: [Name, credentials. Department, Institution, "
    "City, Country. Email: email@institution.edu]"
)
run.font.size = Pt(11)

doc.add_page_break()


# ── Abstract ──────────────────────────────────────────────────────────────────

add_heading(doc, "Abstract", level=1)

add_heading(doc, "Background", level=2)
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor "
    "incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud "
    "exercitation ullamco laboris.")
# TODO: state the gap in knowledge and the study objective (~2 sentences)

add_heading(doc, "Methods", level=2)
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in "
    "reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.")
# TODO: study design, sample, exposures, outcome, analytic approach

add_heading(doc, "Results", level=2)
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Excepteur sint occaecat "
    "cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
# TODO: primary results with numbers and confidence intervals

add_heading(doc, "Conclusions", level=2)
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam liber tempor cum soluta "
    "nobis eligend optio cumque nihil impedit quo minus.")
# TODO: one sentence on what was found, one on implication

# Keywords
doc.add_paragraph()
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.LEFT
set_line_spacing(p)
run = p.add_run("Keywords: [keyword 1]; [keyword 2]; [keyword 3]; [keyword 4]; [keyword 5]")
run.font.size = Pt(11)
run.italic = True

doc.add_page_break()


# ═══════════════════════════════════════════════════════════════════════════════
# INTRODUCTION
# ═══════════════════════════════════════════════════════════════════════════════

add_heading(doc, "Introduction", level=1)

# TODO: Para 1 — establish the problem / burden
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor "
    "incididunt ut labore et dolore magna aliqua.")

# TODO: Para 2 — what is known; limitations of existing approaches
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, "
    "quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.")

# TODO: Para 3 — the gap this study addresses
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in "
    "reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.")

# TODO: Para 4 — aims and hypotheses
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Excepteur sint occaecat "
    "cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")


# ═══════════════════════════════════════════════════════════════════════════════
# METHODS
# ═══════════════════════════════════════════════════════════════════════════════

add_heading(doc, "Methods", level=1)

add_heading(doc, "Study Design and Participants", level=2)
# TODO: cohort, visits, follow-up period, ethics
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut perspiciatis unde "
    "omnis iste natus error sit voluptatem accusantium doloremque laudantium.")

add_heading(doc, "Measures", level=2)
# TODO: exposure(s), outcome(s), covariates — one subsection each if needed
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nemo enim ipsam voluptatem "
    "quia voluptas sit aspernatur aut odit aut fugit.")

add_heading(doc, "Statistical Analysis", level=2)
# TODO: analytic approach, software, significance threshold
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minima veniam, "
    "quis nostrum exercitationem ullam corporis suscipit laboriosam.")


# ═══════════════════════════════════════════════════════════════════════════════
# RESULTS
# ═══════════════════════════════════════════════════════════════════════════════

add_heading(doc, "Results", level=1)

add_heading(doc, "Sample Characteristics", level=2)
# TODO: N, age, sex, race breakdown; follow-up time
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis autem vel eum iure "
    "reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.")

add_heading(doc, "Primary Analysis", level=2)
# TODO: main result with effect estimates and confidence intervals
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. At vero eos et accusamus "
    "et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti.")

add_heading(doc, "Secondary Analyses", level=2)
# TODO: secondary/sensitivity results
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero tempore, cum "
    "soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime.")


# ═══════════════════════════════════════════════════════════════════════════════
# DISCUSSION
# ═══════════════════════════════════════════════════════════════════════════════

add_heading(doc, "Discussion", level=1)

# TODO: Para 1 — summary of principal findings
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Temporibus autem quibusdam "
    "et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates.")

# TODO: Para 2 — interpretation of primary finding in context of prior literature
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Itaque earum rerum hic "
    "tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur.")

# TODO: Para 3 — biological plausibility / mechanistic interpretation
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis autem vel eum iure "
    "reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.")

# TODO: Para 4 — clinical/public health implications
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. At vero eos et accusamus "
    "et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti.")

add_heading(doc, "Strengths and Limitations", level=3)
# TODO: 2-3 strengths, 3-4 limitations
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam libero tempore cum "
    "soluta nobis eligendi optio cumque nihil impedit quo minus id quod maxime placeat.")

add_heading(doc, "Conclusion", level=3)
# TODO: 2-3 sentences: what was found, what it means, what it enables
add_para(doc,
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Temporibus autem quibusdam "
    "et aut officiis debitis aut rerum necessitatibus saepe eveniet.")

doc.add_page_break()


# ═══════════════════════════════════════════════════════════════════════════════
# REFERENCES
# ═══════════════════════════════════════════════════════════════════════════════

add_heading(doc, "References", level=1)

def _render_ref_numbered(p, number, annote):
    p.add_run(f"{number}. ").font.size = Pt(12)
    parts = re.split(r'\*(.+?)\*', annote)
    for j, part in enumerate(parts):
        run = p.add_run(part)
        run.font.size = Pt(12)
        if j % 2 == 1:
            run.italic = True

if CITATION_STYLE == "numbered":
    ordered_keys = _cite_order
elif CITATION_STYLE == "author-year":
    ordered_keys = sorted(_cite_order, key=lambda k: _bib.get(k, {}).get('author', '').lower())
else:
    ordered_keys = sorted(_cite_order, key=lambda k: k.lower())

for i, key in enumerate(ordered_keys, start=1):
    entry = _bib.get(key, {})
    annote = entry.get('annote', key)
    p = doc.add_paragraph()
    set_line_spacing(p)
    _render_ref_numbered(p, i, annote)
    p.paragraph_format.left_indent       = Cm(0.6)
    p.paragraph_format.first_line_indent = Cm(-0.6)


# ── Save ──────────────────────────────────────────────────────────────────────

validate_citations(set(_cite_order), _bib)
doc.save(OUTFILE)
print(f"Saved: {OUTFILE}")

# Write cite_map.json for /literature:endnote-link
import json as _json
_cite_map_path = os.path.join(HERE, "references", "cite_map.json")
with open(_cite_map_path, "w", encoding="utf-8") as _f:
    _json.dump(
        {slug: {"number": _cites[slug], "doi": _bib.get(slug, {}).get("doi", "")}
         for slug in _cite_order},
        _f, indent=2
    )
print(f"Cite map : {_cite_map_path}")
